//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 LQ_Testbed.rc 使用
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_LQ_TESTBED_DIALOG           102
#define IDR_TOOLBAR                     102
#define IDS_STRING102                   102
#define IDS_STRING103                   103
#define IDS_STRING104                   104
#define IDS_STRING105                   105
#define IDS_STRING106                   106
#define IDS_STRING107                   107
#define IDD_OPTION_DLG                  108
#define IDS_STRING108                   108
#define IDS_STRING109                   109
#define IDS_STRING110                   110
#define IDR_MAINFRAME                   128
#define IDI_ICON1                       129
#define IDI_ICON2                       130
#define IDI_ICON3                       131
#define IDI_ICON4                       132
#define IDI_ICON5                       133
#define IDI_ICON6                       134
#define IDI_ICON7                       135
#define IDR_MENU                        136
#define IDD_NODEMANAGE_DLG              138
#define IDD_NEWTEST_DLG                 139
#define IDD_TESTCUSTOM_DLG              140
#define IDD_EVALUATORMANAGE_DLG         141
#define IDD_LINKESTIMATE_DLG            142
#define IDD_EVALUATORANALYSIS           150
#define IDI_ICON8                       151
#define IDI_ICON9                       152
#define IDD_DATAMANAGE_DLG              166
#define IDB_BITMAP1                     169
#define IDD_SCENECONFIG_DLG             170
#define IDD_TESTRESULTDISPLAY_DLG       172
#define IDB_BITMAP2                     174
#define IDD_DISPLAYTOPOLOGY             181
#define IDD_DISPLAYTOPOLOGY_DLG         181
#define IDD_POWER_DLG                   183
#define IDC_LIST_NODES                  1000
#define IDC_IPLOTX                      1001
#define IDC_RADIO1                      1002
#define IDC_EDIT_IPADDRESS              1002
#define IDC_RADIO2                      1003
#define IDC_EDIT_DATABASENAME           1003
#define IDC_RADIO3                      1004
#define IDC_EDIT_PSW                    1004
#define IDC_EDIT_USER                   1005
#define IDC_RADIO_TIME2SNRDOWN          1005
#define IDC_COMBO_SERIALBAUD            1006
#define IDC_LIST_PACKETINFO             1006
#define IDC_RADIO_TIME2LQIUP            1006
#define IDC_COMBO_SERIALPORT            1007
#define IDC_RADIO_TIME2LQIDOWN          1007
#define IDC_EDIT1                       1008
#define IDC_RADIO_TIME2SNRUP            1008
#define IDC_COMBO_NODEID                1009
#define IDC_EDIT3                       1009
#define IDC_EDIT2                       1010
#define IDC_COMBO_TESTMODEL             1011
#define IDC_EDIT_SENDRATE               1012
#define IDC_EDIT_TESTTIME               1013
#define IDC_LIST1                       1015
#define IDC_BUTTON1                     1016
#define IDC_BUTTON2                     1017
#define IDC_BUTTON3                     1018
#define IDC_LIST_NODEINFO               1020
#define IDC_EDIT_NODENO                 1021
#define IDC_EDIT_NODEID                 1021
#define IDC_EDIT_VOLTAGE                1022
#define IDC_COMBO_LOCATION              1023
#define IDC_COMBO_POWER                 1024
#define IDC_COMBO_SENDPOWER             1024
#define IDC_EDIT_CHAIN                  1025
#define IDC_EDIT_DISTANCE               1026
#define IDC_BTN_CLOSE                   1027
#define IDC_BTN_RESTART                 1028
#define IDC_BTN_CLOSEALL                1029
#define IDC_BTN_RESTARTALL              1030
#define IDC_BTN_BACK                    1031
#define IDC_EDIT_PACKETS                1032
#define IDC_BTN_ADD                     1033
#define IDC_COMBO_STATE                 1033
#define IDC_BTN_DELETE                  1034
#define IDC_EDIT_TYPE                   1034
#define IDC_BTN_SENDCOMMAND             1035
#define IDC_LIST_CUSTOMINFO             1036
#define IDC_LIST_LOG                    1037
#define IDC_BTN_COMMANDTEST             1038
#define IDC_BTN_PREPROCESS              1039
#define IDC_EDIT_TESTID                 1042
#define IDC_BTN_NEWTEST                 1043
#define IDC_EDIT_MSGSUM                 1044
#define IDC_BTN_CONFIG                  1045
#define IDC_DATETIMEPICKER_EDATE        1048
#define IDC_DATETIMEPICKER_ETIME        1049
#define IDC_BTN_SUBMIT                  1050
#define IDC_EDIT_T                      1051
#define IDC_BTN_CLEARTESTINFO           1052
#define IDC_DATETIMEPICKER_SDATE        1052
#define IDC_BTN_CLEARPACKETINFO         1053
#define IDC_DATETIMEPICKER_STIME        1053
#define IDC_BTN_EXPORTTESTINFO          1054
#define IDC_EDIT_SENDPERIOD             1054
#define IDC_EDIT_TITLE                  1055
#define IDC_STATIC_CURTIME              1057
#define IDC_BTN_DELTE                   1058
#define IDC_COMBO1                      1059
#define IDC_COMBO_CHANNEL               1059
#define IDC_COMBO_SCENE                 1059
#define IDC_IPLOTX1                     1060
#define IDC_IPLOTX_RESULT               1060
#define IDC_BTN_CANCEL                  1061
#define IDC_COMBO_SCHEDULE              1061
#define IDC_EDIT_SCENEDISCRIBE          1062
#define IDC_BTN_OK                      1063
#define IDC_COMBO_OLD                   1064
#define IDC_RADIO_FUNCTION              1065
#define IDC_EDIT_SCENENAME              1066
#define IDC_BTN_DELETESCENE             1067
#define IDC_RADIO_SHOWCURINFO           1068
#define IDC_BTN_WITHDRAW                1069
#define IDC_STATIC_TIME                 1070
#define IDC_RADIO_ACTIVE                1073
#define IDC_RADIO5                      1074
#define IDC_LIST_RESULT                 1075
#define IDC_BTN_BACKUP                  1076
#define IDC_BTN_RESTORE                 1077
#define IDC_BTN_DELETEDATA              1078
#define IDC_RADIO_TIME2PRR              1080
#define IDC_COMBO_SCENENAME             1082
#define IDC_EDIT_ENDTIME                1083
#define IDC_EDIT_SENDPACKETS            1086
#define IDC_EDIT_TESTPERIOD             1087
#define IDC_EDIT_TESTMODE               1088
#define IDC_EDIT_SCENEDESCRIBE          1089
#define IDC_RADIO_TIME2RSSIDOWN         1090
#define IDC_RADIO_TIME2RSSIUP           1091
#define IDC_BTN_EXPORTSCENEINFO         1093
#define IDC_BTN_EXPORTSCHEDULE          1094
#define IDC_BTN_EXPORTNODEINFO          1095
#define IDC_BTN_PACKETINFO              1096
#define IDC_BTN_EXPORT                  1097
#define IDC_EDIT_SCENEDESCRIBLE         1098
#define ID_MENUITEM32772                32772
#define ID_MENU_BASESET                 32773
#define ID_MENU_START                   32774
#define ID_MENU_CLOSE                   32775
#define ID_MENU_EXIT                    32776
#define ID_MENU_TESTCUSTOM              32777
#define ID_MENU_NODEMANAGE              32778
#define ID_MENU_NETCONFIG               32778
#define ID_MENU_DATAMANAGE              32779
#define ID_MENUITEM32780                32780
#define ID_MENU_ESTIMATIONS             32780
#define ID_MENU_STARTTEST               32781
#define ID_MENU_CURRESULT               32783
#define ID_MENU_OLDRESULT               32784
#define ID_MENU_LQP                     32785
#define ID_32786                        32786
#define ID_MENU_DISPLAYTOPOLOGY         32787
#define ID_MENU_POWER                   32788
#define ID_MENU_TOPOLOGY                32789
#define ID_MENU_EXPORTDATA              65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        186
#define _APS_NEXT_COMMAND_VALUE         32790
#define _APS_NEXT_CONTROL_VALUE         1099
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
